# Generated by Django 3.2.7 on 2022-01-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0002_alter_greeting_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=42)),
                ('taskID', models.IntegerField()),
                ('userAnswer', models.CharField(max_length=42)),
                ('taskCorrectAnswered', models.BooleanField()),
                ('prototype', models.IntegerField()),
                ('answerDate', models.DateField()),
                ('overallMouseClicksCounter', models.IntegerField()),
                ('clickOnCalendarCounter', models.IntegerField()),
                ('clickOnDaysCounter', models.IntegerField()),
                ('timeNeededForTask', models.FloatField()),
            ],
        ),
    ]
