# Generated by Django 3.2.7 on 2022-01-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datepicker', '0003_usertaskdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskdata',
            name='answerDate',
            field=models.CharField(max_length=42),
        ),
    ]
